import Head from "next/head";
import Image from "next/image";
import NewsCard from "../components/NewsCard";
import homeStyles from "../styles/Home.module.scss";

export default function Home({ feeds }) {
  let articles = feeds.articles;
  return (
    <div className={homeStyles.container}>
      <Head>
        <title>My News Site</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={homeStyles.main}>
          {articles.map((elem, index) => (
            <NewsCard key={index} news={elem} />
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    `https://newsapi.org/v2/top-headlines?sources=abc-news&apiKey=${process.env.API_KEY}`
  );
  const feeds = await res.json();
  return { props: { feeds } };
}
